Insert into KeyWord (nameKeyWord) value ( 'consoleJeuxVideo');
Insert into KeyWord (nameKeyWord) value ( 'BandeDessinee');
Insert into KeyWord (nameKeyWord) value ( 'jeuxvideo');
Insert into KeyWord (nameKeyWord) value ( 'MusiqueRap');
Insert into KeyWord (nameKeyWord) value ( 'MusiqueRock');
Insert into KeyWord (nameKeyWord) value ( 'Smartphone');
Insert into KeyWord (nameKeyWord) value ('AppareilPhoto');
Insert into KeyWord (nameKeyWord) value ( 'EcouteurMusique');
Insert into KeyWord (nameKeyWord) value ( 'Ecran');
Insert into KeyWord (nameKeyWord) value ( 'Fast-Food');
Insert into KeyWord (nameKeyWord) value ( 'equipement randonnée');
Insert into KeyWord (nameKeyWord) value ( 'beauté');

Insert into Product (productReference, price, keyword) value ( 'Television 50cm Asus LG152', 450, 9);
Insert into Product (productReference, price, keyword) value ( 'Nintendo Switch', 299, 1);
Insert into product (productReference, price, keyword) value ( 'Playstation 4 pro', 399.99, 1);
Insert into product (productReference, price, keyword) value ( 'xbox one X', 499.99, 1);
Insert into product (productReference, price, keyword) value ( 'Nintendo 3ds', 120.99,1);
Insert into product (productReference, price, keyword) value ( 'Tome 6 Asterix', 9.99, 2);
Insert into product (productReference, price, keyword) value ( 'Tome 7 Asterix', 9.99, 2);
Insert into product (productReference, price, keyword) value ( 'Tome 1 The walking dead', 12.50, 2);
Insert into product (productReference, price, keyword) value ( 'Tome 2 The walkin dead', 12.50, 2);
Insert into product (productReference, price, keyword) value ( 'Tome 3 The walkin dead', 12.50, 2);
Insert into product (productReference, price, keyword) value ( 'Tome 5 The walking dead', 12.50, 2);
Insert into product (productReference, price, keyword) value ( 'Tome 6 The walking dead', 12.50, 2);
Insert into product (productReference, price, keyword) value ( 'Tome 7 The walking dead', 12.50, 2);
Insert into product (productReference, price, keyword) value ( 'Tome 8 The walking dead', 12.50, 2);
Insert into product (productReference, price, keyword) value ( 'Tome 9 The walking dead', 12.50, 2);
Insert into product (productReference, price, keyword) value ( 'god of war', 69.99, 3);
Insert into product (productReference, price, keyword) value ( 'fifa 18', 69.99, 3);
Insert into product (productReference, price, keyword) value ( 'Shadow of the colossus', 69.99, 3);
Insert into product (productReference, price, keyword) value ( 'zelda botw', 49.99, 3);
Insert into product (productReference, price, keyword) value ( 'gta V', 69.99, 3);
Insert into product (productReference, price, keyword) value ( 'Mario kart 8', 39.99, 3);
Insert into product (productReference, price, keyword) value ( 'metal gear solid 5', 29.99, 3);
Insert into product (productReference, price, keyword) value ( 'Rayman legend', 19.99, 3);
Insert into product (productReference, price, keyword) value ( 'Nekfeu humanoide', 15.99, 4);
Insert into product (productReference, price, keyword) value ( 'Booba trone', 15.99, 4);
Insert into product (productReference, price, keyword) value ( 'Kendrick lama DAMN', 15.99, 4);
Insert into product (productReference, price, keyword) value ( 'IAM ecole mic argent', 15.99, 4);
Insert into product (productReference, price, keyword) value ( 'The beatles help', 15.99, 5);
Insert into product (productReference, price, keyword) value ( 'SOAD toxicity', 15.99, 5);
Insert into product (productReference, price, keyword) value ( 'Muse resistance', 15.99, 5);
Insert into product (productReference, price, keyword) value ( 'Nirvana Bleach', 15.99, 5);
Insert into product (productReference, price, keyword) value ( 'Samsung S9+', 850.99, 6);
Insert into product (productReference, price, keyword) value ( 'Iphone X', 1199.99, 6);
Insert into product (productReference, price, keyword) value ( 'Wiko 7p', 159.99, 6);
Insert into product (productReference, price, keyword) value ( 'Canon e354x', 999.99, 7);
Insert into product (productReference, price, keyword) value ( 'Nikon EARTZ', 1600.99, 7);
Insert into product (productReference, price, keyword) value ( 'Olympus 78A', 600.99, 7);
Insert into product (productReference, price, keyword) value ( 'Bose surround 35', 399.99, 8);
Insert into product (productReference, price, keyword) value ( 'Beats studio pro', 350.99, 8);
Insert into product (productReference, price, keyword) value ( 'Monitor 50cm Asus LG152', 450.99, 9);
Insert into product (productReference, price, keyword) value ( 'Television 122cm Sony bravia', 699.99, 9);
Insert into product (productReference, price, keyword) value ( 'Television 130 cm 4k samsung evo2', 899.99, 9);
Insert into product (productReference, price, keyword) value ( 'Sandwich jambon beurre deau-nah', 3, 10);
Insert into product (productReference, price, keyword) value ( 'Big Mac', 6.99, 10);
Insert into product (productReference, price, keyword) value ( 'otacos xl', 10.99, 10);
Insert into product (productReference, price, keyword) value ( 'pizza vapiano', 17.99, 10);
Insert into product (productReference, price, keyword) value ( 'Sandwich saumon deau-nah', 6.50, 10);
Insert into product (productReference, price, keyword) value ( 'Sandwich poulet deau-nah', 4.99, 10);
Insert into product (productReference, price, keyword) value ( 'Sandwich dinde deau-nah', 3.99, 10);
Insert into product (productReference, price, keyword) value ( 'Glace italienne jeff', 4.50, 10);
Insert into product (productReference, price, keyword) value ( 'Coca-cola 50cl', 2.50, 10);
Insert into product (productReference, price, keyword) value ( 'petite frite mcdo', 1.99, 10);
Insert into product (productReference, price, keyword) value ( 'grande frite mcdo', 2.99, 10);
Insert into product (productReference, price, keyword) value ( 'McFlurry', 4.99, 10);
Insert into product (productReference, price, keyword) value ( 'chaussure north face solar', 299.99, 11);
Insert into product (productReference, price, keyword) value ( 'pull quechua laine', 9.99, 11);
Insert into product (productReference, price, keyword) value ( 'tente quechua 3 places', 110.99, 11);
Insert into product (productReference, price, keyword) value ( 'sac à dos Columbia 50L', 150.99, 11);
Insert into product (productReference, price, keyword) value ( 'rouge a levre 20 chanel', 30.99, 12);
Insert into product (productReference, price, keyword) value ( 'gel douche Carrefour', 2.99, 12);
Insert into product (productReference, price, keyword) value ( 'déodorant rexona man', 5.99, 12);
Insert into product (productReference, price, keyword) value ( 'mascara dior', 35.99, 12);
Insert into product (productReference, price, keyword) value ( 'dentifrice signal', 3.52, 12);

Insert into typeprofile(ProfileName) value ( 'CulturePop');
Insert into typeprofile(ProfileName) value ( 'Photographie');
Insert into typeprofile(ProfileName) value ( 'Musique');
Insert into typeprofile(ProfileName) value ( 'Gourmand');
Insert into typeprofile(ProfileName) value ( 'NouvelleTechnologie');
Insert into typeprofile(ProfileName) value ( 'coquet');
Insert into typeprofile(ProfileName) value ( 'CulturePop');
Insert into typeprofile(ProfileName) value ( 'Sportif');

Insert into linktpkeyword (idKeyWord, idTypeProfile) value( 1,1);
Insert into linktpkeyword (idKeyWord, idTypeProfile) value( 2,1);
Insert into linktpkeyword (idKeyWord, idTypeProfile) value( 3,1);
Insert into linktpkeyword (idKeyWord, idTypeProfile) value( 4,3);
Insert into linktpkeyword (idKeyWord, idTypeProfile) value( 5,3);
Insert into linktpkeyword (idKeyWord, idTypeProfile) value( 6,5);
Insert into linktpkeyword (idKeyWord, idTypeProfile) value( 7,2);
Insert into linktpkeyword (idKeyWord, idTypeProfile) value( 8,3);
Insert into linktpkeyword (idKeyWord, idTypeProfile) value( 9,5);
Insert into linktpkeyword (idKeyWord, idTypeProfile) value( 10,4);
Insert into linktpkeyword (idKeyWord, idTypeProfile) value( 11,8);
Insert into linktpkeyword (idKeyWord, idTypeProfile) value( 12,6);
Insert into linktpkeyword (idKeyWord, idTypeProfile) value( 1,5);

Insert into Client(pseudo, password, clientName, clientSurname, phone, address, gender) value('ilies123','ilies123', 'faddaoui', 'ilies', '0618622953', '5 rue a', 'm');
Insert into Client(pseudo, password, clientName, clientSurname, phone, address, gender) value('bertrand123','bertrand123', 'renard', 'bertrand','0618156154', '4 rue b', 'm');
Insert into Client(pseudo, password, clientName, clientSurname, phone, address, gender) value('robert123','robert123', 'robert', 'redford','06235288', '6 rue b', 'm');
Insert into Client(pseudo, password, clientName, clientSurname, phone, address, gender) value('bea123','bea123', 'beatrice', 'solide','054175120', '8 rue 8', 'f');
Insert into Client(pseudo, password, clientName, clientSurname, phone, address, gender) value('jeanne123','jeanne123', 'jeanne', 'rapouille','026522311', '8 rue dart', 'f');
Insert into Client(pseudo, password, clientName, clientSurname, phone, address, gender) value('farid123','farid123', 'farid', 'benarfa','09175120', '6 rue courneuse', 'm');
Insert into Client(pseudo, password, clientName, clientSurname, phone, address, gender) value('fatou123','fatou123', 'fatoumata', 'benarfa','09175120', '6 rue courneuse', 'f');
Insert into Client(pseudo, password, clientName, clientSurname, phone, address, gender) value('Wong123','Wong123', 'Wong', 'shihao','0615263659', '8 rue lajoulie', 'f');
Insert into Client(pseudo, password, clientName, clientSurname, phone, address, gender) value('adam123','adam123', 'adamska', 'Shalaskala','0501020302', '8 rue 4 mai', 'm');
Insert into Client(pseudo, password, clientName, clientSurname, phone, address, gender) value('jojo123','jojo123', 'john', 'doe','0502030214', '8 rue zero', '?');

Insert into linkclienttp(idTypeProfile,idClient) value ( 4,1);
Insert into linkclienttp(idTypeProfile,idClient) value( 1,1);
Insert into linkclienttp(idTypeProfile,idClient) value( 5,1);

Insert into PurchaseHistory(idProduct, idClient, purchaseDate, Quantity) value ( 1, 1, date(sysdate()), 1);
Insert into PurchaseHistory(idProduct, idClient, purchaseDate, Quantity) value ( 2, 1, date(sysdate()), 1);
Insert into PurchaseHistory(idProduct, idClient, purchaseDate, Quantity) value ( 1, 1, date(sysdate()), 1);
Insert into PurchaseHistory(idProduct, idClient, purchaseDate, Quantity) value ( 53, 1, date(sysdate()), 1);
Insert into PurchaseHistory(idProduct, idClient, purchaseDate, Quantity) value ( 44, 1, date(sysdate()), 1);
Insert into PurchaseHistory(idProduct, idClient, purchaseDate, Quantity) value ( 19, 1, date(sysdate()), 1);
Insert into PurchaseHistory(idProduct, idClient, purchaseDate, Quantity) value ( 21, 1, date(sysdate()), 1);
Insert into PurchaseHistory(idProduct, idClient, purchaseDate, Quantity) value ( 22, 1, date(sysdate()), 1);
Insert into PurchaseHistory(idProduct, idClient, purchaseDate, Quantity) value ( 37, 1, date(sysdate()), 1);
Insert into PurchaseHistory(idProduct, idClient, purchaseDate, Quantity) value ( 27, 1, date(sysdate()), 1);
Insert into PurchaseHistory(idProduct, idClient, purchaseDate, Quantity) value ( 38, 1, date(sysdate()), 1);
Insert into PurchaseHistory(idProduct, idClient, purchaseDate, Quantity) value ( 10, 1, date(sysdate()), 1);
Insert into PurchaseHistory(idProduct, idClient, purchaseDate, Quantity) value ( 11, 1, date(sysdate()), 1);
Insert into PurchaseHistory(idProduct, idClient, purchaseDate, Quantity) value ( 12, 1, date(sysdate()), 1);
Insert into PurchaseHistory(idProduct, idClient, purchaseDate, Quantity) value ( 13, 1, date(sysdate()), 1);
Insert into PurchaseHistory(idProduct, idClient, purchaseDate, Quantity) value ( 14, 1, date(sysdate()), 1);
Insert into PurchaseHistory(idProduct, idClient, purchaseDate, Quantity) value ( 15, 1, date(sysdate()), 1);
Insert into PurchaseHistory(idProduct, idClient, purchaseDate, Quantity) value ( 63,1, date(sysdate()), 1);
Insert into PurchaseHistory(idProduct, idClient, purchaseDate, Quantity) value ( 20, 1, date(sysdate()), 1);
Insert into PurchaseHistory(idProduct, idClient, purchaseDate, Quantity) value ( 28, 1, date(sysdate()), 1);
Insert into PurchaseHistory(idProduct, idClient, purchaseDate, Quantity) value ( 38, 1, date(sysdate()), 1);
Insert into PurchaseHistory(idProduct, idClient, purchaseDate, Quantity) value ( 39, 1, '16-03-2018', 1);


Insert into Magasin value (1, 'Courir', 'Sport',875);
Insert into Magasin value (2, 'Adidas', 'Sport',700);
Insert into Magasin value (3, 'Foot Locker', 'Sport',734);
Insert into Magasin value (4, 'Nike', 'Sport',735);
Insert into Magasin value (5, 'Go sport', 'Sport',888);
Insert into Magasin value (6, 'Intersport', 'Sport',600);
Insert into Magasin value (7, 'Decathlon', 'Sport',1400);
Insert into Magasin value (23, 'JDsport', 'Sport',943);
Insert into Magasin value (8, 'Fnac', 'Multim�dia',963);
Insert into Magasin value (9, 'Darty', 'Multim�dia',1065);
Insert into Magasin value (10, 'Boulanger', 'Multim�dia',875);
Insert into Magasin value (22, 'Apple', 'Multim�dia',747);
Insert into Magasin value (11, 'H&M', 'Vetement',1000);
Insert into Magasin value (12, 'Devred', 'Vetement',875);
Insert into Magasin value (13, 'Zara', 'Vetement',1176);
Insert into Magasin value (14, 'Celio', 'Vetement',500);
Insert into Magasin value (15, 'C&A', 'Vetement',750);
Insert into Magasin value (16, 'Celio club', 'Vetement',475);
Insert into Magasin value (17, 'Levis', 'Vetement',578);
Insert into Magasin value (18, 'Mango', 'Vetement',765);
Insert into Magasin value (19, 'New look', 'Vetement',654);
Insert into Magasin value (20, 'Primark', 'Vetement',1200);
Insert into Magasin value (21, 'Jules', 'Vetement',624);

Insert into Emplacement value (1, 'A1', 1200, 'Standard', 1.5);
Insert into Emplacement value (2, 'B1', 1500, 'Standard', 2.5);
Insert into Emplacement value (3, 'C1', 750, 'Standard', 11.5);
Insert into Emplacement value (4, 'D1', 1550, 'Standard', 3.0);
Insert into Emplacement value (5, 'A2', 1900, 'Standard', 9.5);
Insert into Emplacement value (5, 'B2', 1700, 'Standard', 7.5);
Insert into Emplacement value (6, 'C2', 800, 'Standard', 1.5);
Insert into Emplacement value (7, 'D2', 600, 'Standard', 0.75);
Insert into Emplacement value (8, 'A3', 700, 'Standard', 1.5);
Insert into Emplacement value (9, 'B3', 1600, 'Standard', 1.5);
Insert into Emplacement value (10, 'C3', 1000, 'Standard', 0.5);
Insert into Emplacement value (11, 'D3', 980, 'Standard', 0.5);


Insert into Stock value (8, 2, 300, '12-04-2018', '28-04-2018', 'retour');
Insert into Stock value (8, 1, 500, '03-12-2017', '16-03-2018', 'retour');
Insert into Stock value (10, 2, 300, '27-08-2017', '16-03-2018', 'livraison');
Insert into Stock value (10, 1, 500, '09-11-2017', '16-05-2018', 'retour');
Insert into Stock value (10, 1, 500, '09-11-2017', '16-05-2018', 'retour');
Insert into Stock value (1, 2, 100, '09-11-2017', '', 'livraison');


Insert into ChiffreDaffaires value ('31/01/2018', 6, 350000);
Insert into ChiffreDaffaires value ('28/02/2018', 6, 400000);
Insert into ChiffreDaffaires value ('31/03/2018', 6, 320000);
Insert into ChiffreDaffaires value ('30/04/2018', 6, 378000);
Insert into ChiffreDaffaires value ('31/01/2018', 7, 250000);
Insert into ChiffreDaffaires value ('28/02/2018', 7, 270000);
Insert into ChiffreDaffaires value ('31/03/2018', 7, 320000);
Insert into ChiffreDaffaires value ('30/04/2018', 7, 248000);


Insert into Frequentation value ('31/01/2018', 12, 3500);
Insert into Frequentation value ('28/02/2018', 12, 6000);
Insert into Frequentation value ('31/03/2018', 12, 4000);
Insert into Frequentation value ('30/04/2018', 12, 3000);
Insert into Frequentation value ('31/01/2018', 13, 2700);
Insert into Frequentation value ('28/02/2018', 13, 5000);
Insert into Frequentation value ('31/03/2018', 13, 3200);
Insert into Frequentation value ('30/04/2018', 13, 2600);


Insert into Bondelivraison value (1, '1,2', 2);
Insert into Bondelivraison value (2, '2,3', 4);