package vue;

import javax.swing.*;
import java.awt.*;

/**
 * @author Ilies , Said
 * @version 1.0
 * This view shows a personal path generated by the server for the user
 */
public class ClientPathView extends JFrame {
    public ClientPathView(int idClient){
        this.setTitle("PhyGit Mall: My personal path");
        this.setSize(new Dimension(600,600));
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        /********************************SAID*************************************************************************/
        // @Said, tu fais ici tes opérations, c'est la fenêtre qui s'ouvre quand tu cliques sur "generate path"
        /**************************************************************************************************************/
    }
}
